sonar.projectKey=shopping_list
sonar.projectName=Shopping List - CorujaTech
sonar.projectVersion=1.0.0

sonar.sources=lib
sonar.tests=test
sonar.sourceEncoding=UTF-8

# Dart/Flutter analyzer
sonar.dart.analyzer.mode=FLUTTER
sonar.dart.analyzer.options.override=false

# Test reports
sonar.flutter.tests.reportPath=tests.output
sonar.flutter.coverage.reportPath=coverage/lcov.info

# Exclusions
sonar.exclusions=**/*.g.dart,**/generated/**
