class CurrencyInfo {
  const CurrencyInfo(this.code, this.name);

  final String code;
  final String name;
}

const List<CurrencyInfo> allCurrencies = [
  CurrencyInfo('AED', 'Dirham dos Emirados'),
  CurrencyInfo('AFN', 'Afegane afegão'),
  CurrencyInfo('ALL', 'Lek albanês'),
  CurrencyInfo('AMD', 'Dram armênio'),
  CurrencyInfo('ANG', 'Florim das Antilhas Holandesas'),
  CurrencyInfo('AOA', 'Kwanza angolano'),
  CurrencyInfo('ARS', 'Peso argentino'),
  CurrencyInfo('AUD', 'Dólar australiano'),
  CurrencyInfo('AWG', 'Florim arubano'),
  CurrencyInfo('AZN', 'Manat azerbaijano'),
  CurrencyInfo('BAM', 'Marco bósnio-herzegovino'),
  CurrencyInfo('BBD', 'Dólar barbadense'),
  CurrencyInfo('BDT', 'Taka bengali'),
  CurrencyInfo('BGN', 'Lev búlgaro'),
  CurrencyInfo('BHD', 'Dinar bareinita'),
  CurrencyInfo('BIF', 'Franco burundiano'),
  CurrencyInfo('BMD', 'Dólar bermudense'),
  CurrencyInfo('BND', 'Dólar bruneano'),
  CurrencyInfo('BOB', 'Boliviano'),
  CurrencyInfo('BRL', 'Real brasileiro'),
  CurrencyInfo('BSD', 'Dólar bahamense'),
  CurrencyInfo('BTN', 'Ngultrum butanês'),
  CurrencyInfo('BWP', 'Pula botsuanesa'),
  CurrencyInfo('BYN', 'Rublo bielorrusso'),
  CurrencyInfo('BZD', 'Dólar belizenho'),
  CurrencyInfo('CAD', 'Dólar canadense'),
  CurrencyInfo('CDF', 'Franco congolês'),
  CurrencyInfo('CHF', 'Franco suíço'),
  CurrencyInfo('CLP', 'Peso chileno'),
  CurrencyInfo('CNY', 'Yuan chinês'),
  CurrencyInfo('COP', 'Peso colombiano'),
  CurrencyInfo('CRC', 'Colón costarriquenho'),
  CurrencyInfo('CUP', 'Peso cubano'),
  CurrencyInfo('CVE', 'Escudo cabo-verdiano'),
  CurrencyInfo('CZK', 'Coroa tcheca'),
  CurrencyInfo('DJF', 'Franco djibutiense'),
  CurrencyInfo('DKK', 'Coroa dinamarquesa'),
  CurrencyInfo('DOP', 'Peso dominicano'),
  CurrencyInfo('DZD', 'Dinar argelino'),
  CurrencyInfo('EGP', 'Libra egípcia'),
  CurrencyInfo('ERN', 'Nakfa eritreia'),
  CurrencyInfo('ETB', 'Birr etíope'),
  CurrencyInfo('EUR', 'Euro'),
  CurrencyInfo('FJD', 'Dólar fijiano'),
  CurrencyInfo('FKP', 'Libra malvinense'),
  CurrencyInfo('GBP', 'Libra esterlina'),
  CurrencyInfo('GEL', 'Lari georgiano'),
  CurrencyInfo('GHS', 'Cedi ganês'),
  CurrencyInfo('GIP', 'Libra de Gibraltar'),
  CurrencyInfo('GMD', 'Dalasi gambiano'),
  CurrencyInfo('GNF', 'Franco guineense'),
  CurrencyInfo('GTQ', 'Quetzal guatemalteco'),
  CurrencyInfo('GYD', 'Dólar guianense'),
  CurrencyInfo('HKD', 'Dólar de Hong Kong'),
  CurrencyInfo('HNL', 'Lempira hondurenha'),
  CurrencyInfo('HRK', 'Kuna croata'),
  CurrencyInfo('HTG', 'Gourde haitiano'),
  CurrencyInfo('HUF', 'Florim húngaro'),
  CurrencyInfo('IDR', 'Rupia indonésia'),
  CurrencyInfo('ILS', 'Novo shekel israelense'),
  CurrencyInfo('INR', 'Rupia indiana'),
  CurrencyInfo('IQD', 'Dinar iraquiano'),
  CurrencyInfo('IRR', 'Rial iraniano'),
  CurrencyInfo('ISK', 'Coroa islandesa'),
  CurrencyInfo('JMD', 'Dólar jamaicano'),
  CurrencyInfo('JOD', 'Dinar jordaniano'),
  CurrencyInfo('JPY', 'Iene japonês'),
  CurrencyInfo('KES', 'Xelim queniano'),
  CurrencyInfo('KGS', 'Som quirguiz'),
  CurrencyInfo('KHR', 'Riel cambojano'),
  CurrencyInfo('KMF', 'Franco comoriano'),
  CurrencyInfo('KPW', 'Won norte-coreano'),
  CurrencyInfo('KRW', 'Won sul-coreano'),
  CurrencyInfo('KWD', 'Dinar kuwaitiano'),
  CurrencyInfo('KYD', 'Dólar das Ilhas Cayman'),
  CurrencyInfo('KZT', 'Tenge cazaque'),
  CurrencyInfo('LAK', 'Kip laosiano'),
  CurrencyInfo('LBP', 'Libra libanesa'),
  CurrencyInfo('LKR', 'Rupia ceilandesa'),
  CurrencyInfo('LRD', 'Dólar liberiano'),
  CurrencyInfo('LSL', 'Loti lesotiano'),
  CurrencyInfo('LYD', 'Dinar líbio'),
  CurrencyInfo('MAD', 'Dirham marroquino'),
  CurrencyInfo('MDL', 'Leu moldavo'),
  CurrencyInfo('MGA', 'Ariary malgaxe'),
  CurrencyInfo('MKD', 'Dinar macedônio'),
  CurrencyInfo('MMK', 'Kyat mianmarense'),
  CurrencyInfo('MNT', 'Tugrik mongol'),
  CurrencyInfo('MOP', 'Pataca macaense'),
  CurrencyInfo('MRU', 'Ouguiya mauritana'),
  CurrencyInfo('MUR', 'Rupia mauriciana'),
  CurrencyInfo('MVR', 'Rupia maldiva'),
  CurrencyInfo('MWK', 'Kwacha malawiana'),
  CurrencyInfo('MXN', 'Peso mexicano'),
  CurrencyInfo('MYR', 'Ringgit malaio'),
  CurrencyInfo('MZN', 'Metical moçambicano'),
  CurrencyInfo('NAD', 'Dólar namibiano'),
  CurrencyInfo('NGN', 'Naira nigeriana'),
  CurrencyInfo('NIO', 'Córdova nicaraguense'),
  CurrencyInfo('NOK', 'Coroa norueguesa'),
  CurrencyInfo('NPR', 'Rupia nepalesa'),
  CurrencyInfo('NZD', 'Dólar neozelandês'),
  CurrencyInfo('OMR', 'Rial omanense'),
  CurrencyInfo('PAB', 'Balboa panamenho'),
  CurrencyInfo('PEN', 'Sol peruano'),
  CurrencyInfo('PGK', 'Kina papuásia'),
  CurrencyInfo('PHP', 'Peso filipino'),
  CurrencyInfo('PKR', 'Rupia paquistanesa'),
  CurrencyInfo('PLN', 'Zloty polonês'),
  CurrencyInfo('PYG', 'Guarani paraguaio'),
  CurrencyInfo('QAR', 'Rial catarense'),
  CurrencyInfo('RON', 'Leu romeno'),
  CurrencyInfo('RSD', 'Dinar sérvio'),
  CurrencyInfo('RUB', 'Rublo russo'),
  CurrencyInfo('RWF', 'Franco ruandês'),
  CurrencyInfo('SAR', 'Riyal saudita'),
  CurrencyInfo('SBD', 'Dólar salomônico'),
  CurrencyInfo('SCR', 'Rupia seichelense'),
  CurrencyInfo('SDG', 'Libra sudanesa'),
  CurrencyInfo('SEK', 'Coroa sueca'),
  CurrencyInfo('SGD', 'Dólar singapuriano'),
  CurrencyInfo('SHP', 'Libra de Santa Helena'),
  CurrencyInfo('SLE', 'Leone serra-leonês'),
  CurrencyInfo('SOS', 'Xelim somali'),
  CurrencyInfo('SRD', 'Dólar surinamês'),
  CurrencyInfo('SSP', 'Libra sul-sudanesa'),
  CurrencyInfo('STN', 'Dobra são-tomense'),
  CurrencyInfo('SVC', 'Colón salvadorenho'),
  CurrencyInfo('SYP', 'Libra síria'),
  CurrencyInfo('SZL', 'Lilangeni suazi'),
  CurrencyInfo('THB', 'Baht tailandês'),
  CurrencyInfo('TJS', 'Somoni tadjique'),
  CurrencyInfo('TMT', 'Manat turcomeno'),
  CurrencyInfo('TND', 'Dinar tunisiano'),
  CurrencyInfo('TOP', 'Paʻanga tonganesa'),
  CurrencyInfo('TRY', 'Lira turca'),
  CurrencyInfo('TTD', 'Dólar trinitário'),
  CurrencyInfo('TWD', 'Novo dólar taiwanês'),
  CurrencyInfo('TZS', 'Xelim tanzaniano'),
  CurrencyInfo('UAH', 'Hryvnia ucraniano'),
  CurrencyInfo('UGX', 'Xelim ugandense'),
  CurrencyInfo('USD', 'Dólar americano'),
  CurrencyInfo('UYU', 'Peso uruguaio'),
  CurrencyInfo('UZS', 'Som uzbeque'),
  CurrencyInfo('VES', 'Bolívar venezuelano'),
  CurrencyInfo('VND', 'Dong vietnamita'),
  CurrencyInfo('VUV', 'Vatu vanuatuense'),
  CurrencyInfo('WST', 'Tala samoana'),
  CurrencyInfo('XAF', 'Franco CFA central'),
  CurrencyInfo('XCD', 'Dólar do Caribe Oriental'),
  CurrencyInfo('XOF', 'Franco CFA ocidental'),
  CurrencyInfo('XPF', 'Franco CFP'),
  CurrencyInfo('YER', 'Rial iemenita'),
  CurrencyInfo('ZAR', 'Rand sul-africano'),
  CurrencyInfo('ZMW', 'Kwacha zambiana'),
  CurrencyInfo('ZWL', 'Dólar zimbabuano'),
];
